language: java

addons:
  sonarcloud:
    organization: amoretti9
    #token:
    #  secure: $SONAR_TOKEN
      
matrix:
  include:
  - jdk: openjdk8
    if: type IN (push) AND type NOT IN (pull_request)
    env: MAVEN_ARGS="-Pjacoco coveralls:report sonar:sonar -Pe2e -Ppit"
    
services:
  - xvfb

install: true

cache:
  directories:
  - $HOME/.m2
  - $HOME/.sonar/cache
  
script:
  - git fetch --unshallow
  - mvn clean verify $MAVEN_ARGS -Dsonar.login=${SONAR_TOKEN}
